version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: beverage_catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
